version: '3'

services:

  auditService:
    image: rh7-artifactory.svs.hpeswlab.net:8443/caf/audit-service:3.1.0-SNAPSHOT
    ports:
      - "${CAF_AUDIT_SERVICE_PORT:-25080}:8080"
    environment:
      CAF_ELASTIC_HOST_AND_PORT: ${ELASTICSEARCH_HOST_AND_PORT:-elasticsearch1:9300}
      CAF_ELASTIC_CLUSTER_NAME: ${ELASTICSEARCH_CLUSTER_NAME:-elasticsearch-cluster}
      CAF_ELASTIC_NUMBER_OF_SHARDS: ${ELASTICSEARCH_NUMBER_OF_SHARDS:-5}
      CAF_ELASTIC_NUMBER_OF_REPLICAS: ${ELASTICSEARCH_NUMBER_OF_REPLICAS:-1}
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
    resources:
      limits:
        cpus: '0.5'
        memory: 512M
      reservations:
        cpus: '0.05'
        memory: 256M	
		